### ISSUE TITLE
Account activation issue

### ISSUE THREAD

**Issue by jakefb** [macropin/django-registration#230]
When I click the activation link in the email I get this error

    'module' object has no attribute 'parse'

**Comment by dicato** [comment]
@jakefb could you provide the full traceback?

**Comment by jakefb** [comment]
Hi @dicato sorry this issue was caused by a template tag I'm using for gravatar profile images. The problem was that urllib.parse doesn't work with python 2.7. I'll close this issue!
