### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'on_delete' with Django 2

### ISSUE THREAD

**Issue by zkan** [macropin/django-registration#336]
Hi there, I'm using `Django==2.0.7` and got the error below:

```
File "/usr/local/lib/python3.7/site-packages/registration/models.py", line 171, in <module>
    class RegistrationProfile(models.Model):
File "/usr/local/lib/python3.7/site-packages/registration/models.py", line 189, in RegistrationProfile
    user = models.OneToOneField(UserModelString(), verbose_name=_('user'))
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

I'm guessing that [on_delete](https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.OneToOneField) is required in Django 2+. The [doc](http://django-registration-redux.readthedocs.io/en/latest/release-notes.html) says it works with Django 2.0. Is there a way or a workaround to fix this?

Any suggestion is very welcome. Thank you!

**Comment by joshblum** [comment]
hey @zkan i think you're on an older version of the library. in the latest library release `2.4` we have the field set: https://github.com/macropin/django-registration/blob/v2.4/registration/models.py#L303 can you confirm what version of the library you're running?

**Comment by zkan** [comment]
@joshblum Oh, I was using the older version. It's working now. Thank you!
